services:
  # Dịch vụ cho ứng dụng FuelPHP
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    container_name: fuelphp_app
    restart: always
    volumes:
      - .:/var/www/html
    ports:
      - "8888:8888"
    environment:
      - FUEL_ENV=development
      # Kết nối đến MySQL trên host
      - DB_CONNECTION_TYPE=pdo
      - DB_HOSTNAME=host.docker.internal
      - DB_PORT=3306
      - DB_DATABASE=fuel_demo_db
      - DB_USERNAME=root
      - DB_PASSWORD=
    command: php -S 0.0.0.0:8888 -t public